// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"belajar-golang-restfull-api/app"
	"belajar-golang-restfull-api/controller"
	"belajar-golang-restfull-api/middleware"
	"belajar-golang-restfull-api/repository"
	"belajar-golang-restfull-api/service"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	categoryRepository := repository.NewCategoryRepository()
	db := app.NewDB()
	validate := validator.New()
	categoryService := service.NewCategoryService(categoryRepository, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	httprouterRouter := app.NewRouter(categoryController)
	authMiddleware := middleware.NewAuthMiddleware(httprouterRouter)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var router = wire.NewSet(app.NewRouter, wire.Bind(new(http.Handler), new(*httprouter.Router)))
